# НИС «Основы анализа данных в Python»

*Алла Тамбовцева*

## Практикум 9. Датафреймы pandas: агрегирование и введение в мультииндексы

В файлах `Dialogue.csv`-`Movies.csv` (источник – Kaggle) сохранена информация по фильмам о Гарри Поттере:

* `Dialogue`: реплика героя в фильме;
* `Dialogue ID`: ID реплики;
* `Chapter ID`: ID сцены, в которой произносится реплика;
* `Chapter Name`: название сцены, в которой произносится реплика;
* `Place ID`: ID локации, где была произнесена реплика;
* `Place Name`: название локации, где была произнесена реплика;
* `Place Category`: тип локации где была произнесена реплика;
* `Character ID`: ID героя;
* `Character Name`: имя героя;
* `Species`, `Gender`, `House`: вид, пол, факультет/школа героя;
* `Patronius`: патронус героя;
* `Wand (Wood)` и `Wand (Core)`: материал и сердцевина палочки героя;
* `Movie Title`: название фильма;
* `Movie ID`: ID фильма;
* `Release Year`, `Runtime`: год выпуска и продолжительность фильма в минутах;
* `Budget` и `Box Office`: бюджет и кассовый сбор фильма.

In [1]:
import pandas as pd

dialog = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyDat25/refs/heads/main/Dialogue.csv")
chapters = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyDat25/refs/heads/main/Chapters.csv")
heroes = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyDat25/refs/heads/main/Characters.csv")
places = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyDat25/refs/heads/main/Places.csv")
movies = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyDat25/refs/heads/main/Movies.csv")

In [2]:
display(dialog.head(3))
display(heroes.head(3))
display(chapters.head(3))
display(places.head(3))
display(movies.head(3))

,Dialogue ID,Chapter ID,Place ID,Character ID,Dialogue
0,1,1,8,4,I should have known that you would be here...P...
1,2,1,8,7,"Good evening, Professor Dumbledore. Are the ru..."
2,3,1,8,4,"I'm afraid so, Professor. The good, and the bad."

,Character ID,Character Name,Species,Gender,House,Patronus,Wand (Wood),Wand (Core)
0,1,Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
1,2,Ron Weasley,Human,Male,Gryffindor,Jack Russell Terrier,NaN,NaN
2,3,Hermione Granger,Human,Female,Gryffindor,Otter,Vine,Dragon Heartstring

   Chapter ID         Chapter Name  Movie ID  Movie Chapter
0           1    Doorstep Delivery         1              1
1           2  The Vanishing Glass         1              2
2           3  Letters from No One         1              3

   Place ID                Place Name Place Category
0         1         Flourish & Blotts   Diagon Alley
1         2  Gringotts Wizarding Bank   Diagon Alley
2         3           Knockturn Alley   Diagon Alley

,Movie ID,Movie Title,Release Year,Runtime,Budget,Box Office
0,1,Harry Potter and the Philosopher's Stone,2001,152,"$125,000,000","$1,002,000,000"
1,2,Harry Potter and the Chamber of Secrets,2002,161,"$100,000,000","$880,300,000"
2,3,Harry Potter and the Prisoner of Azkaban,2004,142,"$130,000,000","$796,700,000"

### Задача 1

Объедините датафреймы `dialog` и `heroes` таким образом, чтобы к каждой реплике героя в `dialog` были добавлены характеристики героя из `heroes`.

Выполните разные варианты объединений (`left`, `right` и `inner`) и сравните результаты. Сохраните результат правильного объединения в датафрейм `one`.

In [3]:
# правильный - сохраняется порядок строк как в dialog

one = dialog.merge(heroes, how = "left", on = "Character ID")
one

,Dialogue ID,Chapter ID,Place ID,Character ID,Dialogue,Character Name,Species,Gender,House,Patronus,Wand (Wood),Wand (Core)
0,1,1,8,4,I should have known that you would be here...P...,Albus Dumbledore,Human,Male,Gryffindor,Phoenix,Elder,Thestral Tail Hair
1,2,1,8,7,"Good evening, Professor Dumbledore. Are the ru...",Minerva McGonagall,Human,Female,Gryffindor,Cat,Fir,Dragon Heartstring
2,3,1,8,4,"I'm afraid so, Professor. The good, and the bad.",Albus Dumbledore,Human,Male,Gryffindor,Phoenix,Elder,Thestral Tail Hair
3,4,1,8,7,And the boy?,Minerva McGonagall,Human,Female,Gryffindor,Cat,Fir,Dragon Heartstring
4,5,1,8,4,Hagrid is bringing him.,Albus Dumbledore,Human,Male,Gryffindor,Phoenix,Elder,Thestral Tail Hair
...,...,...,...,...,...,...,...,...,...,...,...,...
7439,7440,234,71,1,Then Slytherin House will have gained a wonder...,Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
7440,7441,234,71,84,Really?,Albus Potter,Human,Male,Slytherin,NaN,NaN,NaN
7441,7442,234,71,1,Really.,Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
7442,7443,234,71,1,Ready?,Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
7443,7444,234,71,84,Ready.,Albus Potter,Human,Male,Slytherin,NaN,NaN,NaN

In [4]:
# глобально объединение тоже, но теперь главный
# датафрейм heroes, поэтому строки упорядочены по героям,
# идут в том порядке, как в heroes

dialog.merge(heroes, how = "right", on = "Character ID")

,Dialogue ID,Chapter ID,Place ID,Character ID,Dialogue,Character Name,Species,Gender,House,Patronus,Wand (Wood),Wand (Core)
0,22,2,8,1,"Yes, Aunt Petunia.",Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
1,25,2,8,1,"Yes, Uncle Vernon.",Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
2,38,2,8,1,He's asleep!,Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
3,40,2,8,1,Sorry about him. He doesn't understand what it...,Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
4,44,2,8,1,Anytime.,Harry Potter,Human,Male,Gryffindor,Stag,Holly,Phoenix Feather
...,...,...,...,...,...,...,...,...,...,...,...,...
7439,1087,41,71,162,Oy! What do you two think you're doing?,Waiter,NaN,NaN,NaN,NaN,NaN,NaN
7440,357,15,52,163,"Oh, that was wicked, Harry.",Boy 2,NaN,NaN,NaN,NaN,NaN,NaN
7441,528,20,51,164,Go go Gryffindor! Go go Gryffindor! Go go Gryf...,Crowd,NaN,NaN,NaN,NaN,NaN,NaN
7442,508,19,51,165,Yay!,Gryffindors,NaN,NaN,NaN,NaN,NaN,NaN
7443,7048,219,66,166,Protego Maxima... Finato Duri... Repello Inimi...,Professors,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# ключевой датафрейм dialog, герои упорядочиваются 
# в том порядке, в каком они встречаются в dialog
# без повторений (сначала все реплики Дамблдора, 
# затем – все реплики МакГонагалл и т д)

dialog.merge(heroes, how = "inner", on = "Character ID")

,Dialogue ID,Chapter ID,Place ID,Character ID,Dialogue,Character Name,Species,Gender,House,Patronus,Wand (Wood),Wand (Core)
0,1,1,8,4,I should have known that you would be here...P...,Albus Dumbledore,Human,Male,Gryffindor,Phoenix,Elder,Thestral Tail Hair
1,3,1,8,4,"I'm afraid so, Professor. The good, and the bad.",Albus Dumbledore,Human,Male,Gryffindor,Phoenix,Elder,Thestral Tail Hair
2,5,1,8,4,Hagrid is bringing him.,Albus Dumbledore,Human,Male,Gryffindor,Phoenix,Elder,Thestral Tail Hair
3,7,1,8,4,"Ah, Professor, I would trust Hagrid with my life.",Albus Dumbledore,Human,Male,Gryffindor,Phoenix,Elder,Thestral Tail Hair
4,9,1,8,4,"No problems, I trust, Hagrid?",Albus Dumbledore,Human,Male,Gryffindor,Phoenix,Elder,Thestral Tail Hair
...,...,...,...,...,...,...,...,...,...,...,...,...
7439,7435,234,71,84,Dad?,Albus Potter,Human,Male,Slytherin,NaN,NaN,NaN
7440,7437,234,71,84,What if I'm put in Slytherin?,Albus Potter,Human,Male,Slytherin,NaN,NaN,NaN
7441,7439,234,71,84,But just say I am --,Albus Potter,Human,Male,Slytherin,NaN,NaN,NaN
7442,7441,234,71,84,Really?,Albus Potter,Human,Male,Slytherin,NaN,NaN,NaN
7443,7444,234,71,84,Ready.,Albus Potter,Human,Male,Slytherin,NaN,NaN,NaN

### Задача 2

Добавьте признак `Length` – длину реплики, измеренную в символах. 

a. Определите, представители какого факультета/школы (`House`), в среднем, произносят самые длинные реплики.

b. Определите топ-5 героев – представителей факультета/школы из предыдущего пункта, которым принадлежат самые длинные реплики.

In [6]:
# добавляем столбец

one["Length"] = one["Dialogue"].apply(lambda x: len(x))
one["Length"].head()

0    66
1    64
2    48
3    12
4    23
Name: Length, dtype: int64

In [7]:
# внезапно, но это не Гриффиндор с речами Дамблдора,
# а Дурмстранг (Крам заговорил, не иначе)

print(one.groupby("House")["Length"].mean())

House
Beauxbatons Academy of Magic    44.133333
Durmstrang Institute            86.800000
Gryffindor                      50.869994
Hufflepuff                      54.214286
Ravenclaw                       77.833333
Slytherin                       72.422093
Name: Length, dtype: float64

In [8]:
# определяем название (индекс) максимального значения 

top = one.groupby("House")["Length"].mean().idxmax()
print(top)

Durmstrang Institute

In [9]:
# выбираем строки, соответствующие ему, и сортируем
# топ-5 не понадобился, тут всего 5 героев, 
# и самая длинная реплика принадлежит Гриндевальду

one[one["House"] == top].sort_values("Length", ascending = False)

,Dialogue ID,Chapter ID,Place ID,Character ID,Dialogue,Character Name,Species,Gender,House,Patronus,Wand (Wood),Wand (Core),Length
6644,6645,204,68,98,"Can't you guess, Tom? It lies with him, of co...",Gellert Grindelwald,Human,Male,Durmstrang Institute,NaN,NaN,NaN,161
6640,6641,204,68,98,"Ah, Tom, I thought you would come one day. Bu...",Gellert Grindelwald,Human,Male,Durmstrang Institute,NaN,NaN,NaN,102
6642,6643,204,68,98,"You're so innocent, Tom. Like a schoolboy. T...",Gellert Grindelwald,Human,Male,Durmstrang Institute,NaN,NaN,NaN,84
3086,3087,116,51,114,You have no business here. This tent is for ch...,Viktor Krum,Human,Male,Durmstrang Institute,NaN,NaN,NaN,66
3482,3483,130,58,114,Write to me. Promise.,Viktor Krum,Human,Male,Durmstrang Institute,NaN,NaN,NaN,21

### Задача 3

Определите, кто чаще называет Того-Кого-Нельзя-Называть Волан-де-Мортом: Гарри или Дамблдор. Другими словами, сравните количество реплик, содержащих слово `Voldemort`, принадлежащих героям `Harry Potter` и `Albus Dumbledore`.

In [10]:
# вариант 1

chosen_one = one[one["Character Name"] == "Harry Potter"]
great_man_dumbledore = one[one["Character Name"] == "Albus Dumbledore"]

# Гарри

print(chosen_one["Dialogue"].str.contains("Voldemort", 
                                          case = False).sum())
print(great_man_dumbledore["Dialogue"].str.contains("Voldemort", 
                                          case = False).sum())

37
25

In [11]:
# вариант 2

res = one[one["Dialogue"].str.contains("Voldemort", case = False) & 
          one["Character Name"].isin(["Harry Potter", "Albus Dumbledore"])]

# Гарри

res.groupby("Character Name")["Dialogue"].count()

Character Name
Albus Dumbledore    25
Harry Potter        37
Name: Dialogue, dtype: int64

### Задача 4

Объедините датафреймы таким образом, чтобы к каждой реплике была добавлена информация о том, в какой локации она произнесена и в каком фильме.

a. Определите, в каком фильме (`Movie Title`) было задействовано больше всего локаций (`Place Name`). 

b. Сформируйте сводную таблицу, в которой для каждого фильма посчитано, сколько локаций каждого типа (`Place Category`) там задействовано. Используйте функцию `pd.crosstab()`.

In [12]:
full = one.merge(chapters, 
                 on = "Chapter ID").merge(places, 
                                          on = "Place ID").merge(movies, 
                                                                 on = "Movie ID")

In [13]:
# пункт a
# группируем по названию фильма,
# считаем число заполненных ячеек в Place Name,
# находим индекс максимального значения

full.groupby("Movie Title")["Place Name"].count().idxmax()

'Harry Potter and the Order of the Phoenix'

In [14]:
# пункт a: дополнение
# если хочется учесть только уникальные названия локаций,
# чтобы оценить разнообразие локаций

full.groupby("Movie Title")["Place Name"].unique().apply(lambda x: len(x))

Movie Title
Harry Potter and the Chamber of Secrets        26
Harry Potter and the Deathly Hallows Part 1    10
Harry Potter and the Deathly Hallows Part 2    15
Harry Potter and the Goblet of Fire            22
Harry Potter and the Half-Blood Prince         24
Harry Potter and the Order of the Phoenix      18
Harry Potter and the Philosopher's Stone       27
Harry Potter and the Prisoner of Azkaban       19
Name: Place Name, dtype: int64

In [15]:
# пункт b

pd.crosstab(full["Movie Title"], full["Place Category"])

Place Category,Diagon Alley,Dwellings,Hogsmeade,Hogwarts,Other Magical Locations
Movie Title,,,,,
Harry Potter and the Chamber of Secrets,46,146,0,778,16
Harry Potter and the Deathly Hallows Part 1,0,577,0,0,435
Harry Potter and the Deathly Hallows Part 2,81,96,47,399,89
Harry Potter and the Goblet of Fire,0,80,0,608,53
Harry Potter and the Half-Blood Prince,50,164,56,752,48
Harry Potter and the Order of the Phoenix,0,187,44,656,270
Harry Potter and the Philosopher's Stone,59,119,0,689,18
Harry Potter and the Prisoner of Azkaban,68,39,128,622,24

### Задача 5

Выполните пункт b из предыдущей задачи, используя только группировку. Изучите полученный объект и подумайте, как из него извлекать элементы.

In [16]:
res = full.groupby(["Movie Title", "Place Category"])["Place Name"].count()
res

Movie Title                                  Place Category
Harry Potter and the Chamber of Secrets      Diagon Alley                46
                                             Dwellings                  146
                                             Hogwarts                   778
                                             Other Magical Locations     16
Harry Potter and the Deathly Hallows Part 1  Dwellings                  577
                                             Other Magical Locations    435
Harry Potter and the Deathly Hallows Part 2  Diagon Alley                81
                                             Dwellings                   96
                                             Hogsmeade                   47
                                             Hogwarts                   399
                                             Other Magical Locations     89
Harry Potter and the Goblet of Fire          Dwellings                   80
                                             Hogwarts                   608
                                             Other Magical Locations     53
Harry Potter and the Half-Blood Prince       Diagon Alley                50
                                             Dwellings                  164
                                             Hogsmeade                   56
                                             Hogwarts                   752
                                             Other Magical Locations     48
Harry Potter and the Order of the Phoenix    Dwellings                  187
                                             Hogsmeade                   44
                                             Hogwarts                   656
                                             Other Magical Locations    270
Harry Potter and the Philosopher's Stone     Diagon Alley                59
                                             Dwellings                  119
                                             Hogwarts                   689
                                             Other Magical Locations     18
Harry Potter and the Prisoner of Azkaban     Diagon Alley                68
                                             Dwellings                   39
                                             Hogsmeade                  128
                                             Hogwarts                   622
                                             Other Magical Locations     24
Name: Place Name, dtype: int64

### Мультииндексы

Это объект типа `pandas Series`, обычный столбец со значениями, однако индексы здесь более сложные – они состоят из двух уровней, название фильма `Movie Title` и тип локации `Place Category`. Такие индексы называются *мультииндексами*. Разберем столбец на части:

In [17]:
# индексы – тип MultiIndex, внутри пары значений,
# первый элемент в паре – фильм: второй – тип локации

print(res.index)

MultiIndex([(    'Harry Potter and the Chamber of Secrets', ...),
            (    'Harry Potter and the Chamber of Secrets', ...),
            (    'Harry Potter and the Chamber of Secrets', ...),
            (    'Harry Potter and the Chamber of Secrets', ...),
            ('Harry Potter and the Deathly Hallows Part 1', ...),
            ('Harry Potter and the Deathly Hallows Part 1', ...),
            ('Harry Potter and the Deathly Hallows Part 2', ...),
            ('Harry Potter and the Deathly Hallows Part 2', ...),
            ('Harry Potter and the Deathly Hallows Part 2', ...),
            ('Harry Potter and the Deathly Hallows Part 2', ...),
            ('Harry Potter and the Deathly Hallows Part 2', ...),
            (        'Harry Potter and the Goblet of Fire', ...),
            (        'Harry Potter and the Goblet of Fire', ...),
            (        'Harry Potter and the Goblet of Fire', ...),
            (     'Harry Potter and the Half-Blood Prince', ...),
            (     'Harry Potter and the Half-Blood Prince', ...),
            (     'Harry Potter and the Half-Blood Prince', ...),
            (     'Harry Potter and the Half-Blood Prince', ...),
            (     'Harry Potter and the Half-Blood Prince', ...),
            (  'Harry Potter and the Order of the Phoenix', ...),
            (  'Harry Potter and the Order of the Phoenix', ...),
            (  'Harry Potter and the Order of the Phoenix', ...),
            (  'Harry Potter and the Order of the Phoenix', ...),
            (   'Harry Potter and the Philosopher's Stone', ...),
            (   'Harry Potter and the Philosopher's Stone', ...),
            (   'Harry Potter and the Philosopher's Stone', ...),
            (   'Harry Potter and the Philosopher's Stone', ...),
            (   'Harry Potter and the Prisoner of Azkaban', ...),
            (   'Harry Potter and the Prisoner of Azkaban', ...),
            (   'Harry Potter and the Prisoner of Azkaban', ...),
            (   'Harry Potter and the Prisoner of Azkaban', ...),
            (   'Harry Potter and the Prisoner of Azkaban', ...)],
           names=['Movie Title', 'Place Category'])

In [18]:
# значения – просто числовой массив
# количество локаций

print(res.values)

[ 46 146 778  16 577 435  81  96  47 399  89  80 608  53  50 164  56 752
  48 187  44 656 270  59 119 689  18  68  39 128 622  24]

Как выбирать элементы по индексам, если индексы теперь записаны парами? Если нужно значение из конкретной  ячейки – парами и выбирать:

In [19]:
# название фильма, затем – тип локации

print(res[("Harry Potter and the Chamber of Secrets", "Hogwarts")])
print(res[("Harry Potter and the Philosopher's Stone", "Diagon Alley")])

778
59

Если нужно несколько значений, например, все данные по фильму `Harry Potter and the Chamber of Secrets`, можно воспользоваться `.loc` и срезами. При работе с датафреймом в `.loc` мы указывали название/номер строки и название столбца, а здесь, раз мы имеем дело с одним столбцом, на первом месте мы можем указать индекс первого уровня (навзание фильма), а на втором – индекс второго уровня (тип локации):

In [20]:
# первый уровень – название фильма
# второй уровень – все типы локаций

res.loc["Harry Potter and the Chamber of Secrets", :]

Movie Title                              Place Category
Harry Potter and the Chamber of Secrets  Diagon Alley                46
                                         Dwellings                  146
                                         Hogwarts                   778
                                         Other Magical Locations     16
Name: Place Name, dtype: int64

In [21]:
# первый уровень – все фильмы
# второй уровень – один локации

res.loc[:, "Hogwarts"]

Movie Title
Harry Potter and the Chamber of Secrets        778
Harry Potter and the Deathly Hallows Part 2    399
Harry Potter and the Goblet of Fire            608
Harry Potter and the Half-Blood Prince         752
Harry Potter and the Order of the Phoenix      656
Harry Potter and the Philosopher's Stone       689
Harry Potter and the Prisoner of Azkaban       622
Name: Place Name, dtype: int64

Альтернативный вариант – использование метода `.xs()`:

In [22]:
# выбери данные, где на первом уровне (level = 0)
# указано название фильма Harry Potter and the Chamber of Secrets,
# вместо номера уровня можно вписать его название

print(res.xs("Harry Potter and the Chamber of Secrets", level = 0))
print(res.xs("Harry Potter and the Chamber of Secrets", level = "Movie Title"))

Place Category
Diagon Alley                46
Dwellings                  146
Hogwarts                   778
Other Magical Locations     16
Name: Place Name, dtype: int64
Place Category
Diagon Alley                46
Dwellings                  146
Hogwarts                   778
Other Magical Locations     16
Name: Place Name, dtype: int64

In [23]:
# выбери данные, где на втором уровне (level = 1)
# указано Hogwarts
# вместо номера уровня можно вписать его название

print(res.xs("Hogwarts", level = 1))
print(res.xs("Hogwarts", level = "Place Category"))

Movie Title
Harry Potter and the Chamber of Secrets        778
Harry Potter and the Deathly Hallows Part 2    399
Harry Potter and the Goblet of Fire            608
Harry Potter and the Half-Blood Prince         752
Harry Potter and the Order of the Phoenix      656
Harry Potter and the Philosopher's Stone       689
Harry Potter and the Prisoner of Azkaban       622
Name: Place Name, dtype: int64
Movie Title
Harry Potter and the Chamber of Secrets        778
Harry Potter and the Deathly Hallows Part 2    399
Harry Potter and the Goblet of Fire            608
Harry Potter and the Half-Blood Prince         752
Harry Potter and the Order of the Phoenix      656
Harry Potter and the Philosopher's Stone       689
Harry Potter and the Prisoner of Azkaban       622
Name: Place Name, dtype: int64

### Длинный и широкий формат представления данных

Результат группировки `res` выше – это пример длинного формата представления сгруппированных данных (*long format*). Здесь данные по группам идут друг за другом в один столбец. Сначала идет перечень типов локаций в первом фильме, потом – во втором, и так далее. 

Таблица сопряженности, полученная в задаче 4 – пример широкого формата представления сгруппированных данных (*wide format*). Здесь данные по разным группам записаны в отдельных столбцах (один столбец соответствует одному типу локации):

In [24]:
pd.crosstab(full["Movie Title"], full["Place Category"])

Place Category,Diagon Alley,Dwellings,Hogsmeade,Hogwarts,Other Magical Locations
Movie Title,,,,,
Harry Potter and the Chamber of Secrets,46,146,0,778,16
Harry Potter and the Deathly Hallows Part 1,0,577,0,0,435
Harry Potter and the Deathly Hallows Part 2,81,96,47,399,89
Harry Potter and the Goblet of Fire,0,80,0,608,53
Harry Potter and the Half-Blood Prince,50,164,56,752,48
Harry Potter and the Order of the Phoenix,0,187,44,656,270
Harry Potter and the Philosopher's Stone,59,119,0,689,18
Harry Potter and the Prisoner of Azkaban,68,39,128,622,24

Оба эти формата бывают полезны для разных типов задач, при этом важно помнить, что из одного формата можно всегда получить другой с помощью метода `.unstack()`:

In [25]:
# из длинного в широкий, long to wide,
# образуются пропуски, потому что не все локации есть во всех фильмах

res.unstack()

Place Category,Diagon Alley,Dwellings,Hogsmeade,Hogwarts,Other Magical Locations
Movie Title,,,,,
Harry Potter and the Chamber of Secrets,46.0,146.0,NaN,778.0,16.0
Harry Potter and the Deathly Hallows Part 1,NaN,577.0,NaN,NaN,435.0
Harry Potter and the Deathly Hallows Part 2,81.0,96.0,47.0,399.0,89.0
Harry Potter and the Goblet of Fire,NaN,80.0,NaN,608.0,53.0
Harry Potter and the Half-Blood Prince,50.0,164.0,56.0,752.0,48.0
Harry Potter and the Order of the Phoenix,NaN,187.0,44.0,656.0,270.0
Harry Potter and the Philosopher's Stone,59.0,119.0,NaN,689.0,18.0
Harry Potter and the Prisoner of Azkaban,68.0,39.0,128.0,622.0,24.0

In [26]:
# из широкого в длинный, wide to long

pd.crosstab(full["Movie Title"], full["Place Category"]).unstack()

Place Category           Movie Title
Diagon Alley             Harry Potter and the Chamber of Secrets         46
                         Harry Potter and the Deathly Hallows Part 1      0
                         Harry Potter and the Deathly Hallows Part 2     81
                         Harry Potter and the Goblet of Fire              0
                         Harry Potter and the Half-Blood Prince          50
                         Harry Potter and the Order of the Phoenix        0
                         Harry Potter and the Philosopher's Stone        59
                         Harry Potter and the Prisoner of Azkaban        68
Dwellings                Harry Potter and the Chamber of Secrets        146
                         Harry Potter and the Deathly Hallows Part 1    577
                         Harry Potter and the Deathly Hallows Part 2     96
                         Harry Potter and the Goblet of Fire             80
                         Harry Potter and the Half-Blood Prince         164
                         Harry Potter and the Order of the Phoenix      187
                         Harry Potter and the Philosopher's Stone       119
                         Harry Potter and the Prisoner of Azkaban        39
Hogsmeade                Harry Potter and the Chamber of Secrets          0
                         Harry Potter and the Deathly Hallows Part 1      0
                         Harry Potter and the Deathly Hallows Part 2     47
                         Harry Potter and the Goblet of Fire              0
                         Harry Potter and the Half-Blood Prince          56
                         Harry Potter and the Order of the Phoenix       44
                         Harry Potter and the Philosopher's Stone         0
                         Harry Potter and the Prisoner of Azkaban       128
Hogwarts                 Harry Potter and the Chamber of Secrets        778
                         Harry Potter and the Deathly Hallows Part 1      0
                         Harry Potter and the Deathly Hallows Part 2    399
                         Harry Potter and the Goblet of Fire            608
                         Harry Potter and the Half-Blood Prince         752
                         Harry Potter and the Order of the Phoenix      656
                         Harry Potter and the Philosopher's Stone       689
                         Harry Potter and the Prisoner of Azkaban       622
Other Magical Locations  Harry Potter and the Chamber of Secrets         16
                         Harry Potter and the Deathly Hallows Part 1    435
                         Harry Potter and the Deathly Hallows Part 2     89
                         Harry Potter and the Goblet of Fire             53
                         Harry Potter and the Half-Blood Prince          48
                         Harry Potter and the Order of the Phoenix      270
                         Harry Potter and the Philosopher's Stone        18
                         Harry Potter and the Prisoner of Azkaban        24
dtype: int64