# НИС «Основы анализа данных в Python»

*Алла Тамбовцева*

## Практикум 5. Датафреймы `pandas`: выбор строк и столбцов и простое объединение датафреймов

In [1]:
import pandas as pd

## Часть 1: выбор строк и столбцов с помощью `.loc` и `.iloc`

В файле `nplus1_2025.csv` сохранены характеристики новостей науки с сайта [N+1](https://nplus1.ru/):

* `title`: заголовок новости;
* `author`: автор новости;
* `date`: дата публикации новости;
* `diffc`: сложность новости;
* `rubrics`: рубрики новости;
* `text`: текст новости.

Файл не совсем маленький (~10 Мб), если есть проблемы со скачиванием или загрузкой в Google Colab, его загрузить можно сразу по ссылке (https://raw.githubusercontent.com/allatambov/PyDat25/refs/heads/main/nplus1_2025.csv), скопировав ее в `read_csv()`.

> Загрузите данные из файла `nplus1_2025.csv` и сохраните их в датафрейм `news`.

In [2]:
news = pd.read_csv("nplus1_2025.csv")
news.head()

,Unnamed: 0,title,author,date,diffc,rubrics,text
0,0,Температуру ядра Земли уточнили с помощью лазе...,Егор Конюхов,2025-01-03,2.9,"Физика, Геология",Физики уточнили температуру внутренней границы...
1,1,Большинство людей эпохи мезолита из Оленеостро...,Михаил Подрезов,2025-01-03,3.1,"Археология, Антропология",Ученые проанализировали изотопный состав строн...
2,2,Физики разобрались в состоянии покоя ткани. Он...,Егор Конюхов,2025-01-03,2.3,Физика,"Группа физиков выяснила, что при отсутствии вн..."
3,3,Виноградины усилили микроволновое поле и помог...,Егор Конюхов,2025-01-06,4.1,Физика,Физики использовали две виноградины для усилен...
4,4,Прием глюкокортикоидов при беременности повыси...,Олег Лищук,2025-01-06,1.2,"Медицина, Психология",Кристина Лаугесен (Kristina Laugesen) из Орхус...

Мы уже знаем, что столбец из датафрейма можно выбрать, указав его название в квадратных скобках:

In [3]:
# первые 5 значений столбца diffc

news["diffc"].head()

0    2.9
1    3.1
2    2.3
3    4.1
4    1.2
Name: diffc, dtype: float64

Если столбцов несколько, их названия можно перечислить в квадратных скобках:

In [4]:
news[["title", "diffc", "date"]].head()

                                               title  diffc        date
0  Температуру ядра Земли уточнили с помощью лазе...    2.9  2025-01-03
1  Большинство людей эпохи мезолита из Оленеостро...    3.1  2025-01-03
2  Физики разобрались в состоянии покоя ткани. Он...    2.3  2025-01-03
3  Виноградины усилили микроволновое поле и помог...    4.1  2025-01-06
4  Прием глюкокортикоидов при беременности повыси...    1.2  2025-01-06

> Попробуйте указать в квадратных скобках какое-нибудь целое число – целочисленный индекс столбца или строки. Что получается?

In [5]:
# ничего хорошего не получается
# KeyError – Python ищет 0 
# среди названий столбцов и не находит

# news[0]

Для более универсального выбора строк и столбцов на датафреймах `pandas` определены методы `.loc` и `.iloc`. Название метода `.loc` происходит от *location*, а метода `.iloc` – от *index location*, поэтому:

* `.loc` выбирает элементы по индексам строк (целые числа или текст) и названиям столбцов (текст);
* `.iloc` выбирает элементы по индексам строк (целые числа) и индексам столбцов (целые числа).

Так как эти методы являются дополнением к операторам `[]` для фильтрации, при их вызове тоже используются квадратные скобки, а не круглые. На первом месте в квадратных скобках указываются идентификаторы строк, на втором – идентификаторы столбцов, например:

    news.loc[0, "author"]
    news.iloc[0, 2]
    
> Используя сначала метод `.loc`, а затем `.iloc`, выведите на экран: сложность новости с индексом 50,  заголовок новости с индексом 1727, заголовок новости с индексом 1744.

In [6]:
# на первом месте – индекс строки (номер)
# на втором месте – название столбца

print(news.loc[50, "diffc"])
print(news.loc[1727, "title"])
print(news.loc[1744, "title"])

1.9
Рогатую пчелу из Австралии назвали в честь Люцифера. Рожки растут только у самок этого вида
Орнитологи отпугнули вороватых чаек записями мужского крика. Спокойная речь тоже напугала птиц, но меньше

In [7]:
# на первом месте – индекс строки (номер)
# на втором месте – индекс столбца (номер)

print(news.iloc[50, 4])
print(news.iloc[1727, 1])
print(news.iloc[1744, 1])

1.9
Рогатую пчелу из Австралии назвали в честь Люцифера. Рожки растут только у самок этого вида
Орнитологи отпугнули вороватых чаек записями мужского крика. Спокойная речь тоже напугала птиц, но меньше

> Подумайте, как запросить элементы сразу по нескольким индексам/названиям. Используя `.loc`, выведите значение сложности и автора для новости с индексом 20. Используя `.iloc`, выведите автора и дату новостей с индексами 10, 20, 30.

In [8]:
# если несколько названий – названия внутри списка
# строка с номером 20, столбцы diffc и author

news.loc[20, ["diffc", "author"]]

diffc              2.4
author    Андрей Фокин
Name: 20, dtype: object

**Комментарий.** Pandas выбрал строку с номером 20, из нее – нужный фрагмент со сложностью и именем автора:

|    |   diffc | author       |
|---:|--------:|:-------------|
| 20 |     2.4 | Андрей Фокин |

А затем транспонировал результат – записал строку в виде столбца. Выше в выдаче мы видим последовательность `pandas Series`, столбец с двумя записями: индекс `diffc` и значение 2.4, индекс `author` и значение Андрей Фокин. В названии `Name` сохранен номер строки, которую мы выбрали изначально. А вот с типом столбца все любопытно. В `dtype` написано `object`, Python намекает, что в столбце сохранены текстовые значения. В теории так и должно быть – если в столбце есть и текст, и числа, текстовый тип `object`, как более сильный, должен вытеснить все остальные. Однако в действительности этого не происходит. Хотя Python и написал `object`, значения в последовательности сохранили свои типы:

In [15]:
res = news.loc[20, ["diffc", "author"]]

# сложность осталась числом типа float

print(type(res["diffc"]))
print(type(res["author"]))

<class 'numpy.float64'>
<class 'str'>

Это сделано для удобства – ценность `.loc` и `.iloc` была бы сомнительной, если бы после фильтрации с их помощью пришлось заново «восстанавливать» все типы, чтобы полноценно работать с выбранными фрагментами таблицы.

In [12]:
# строки с номерами 10, 20, 30
# столбцы с номерами 2 и 3

news.iloc[[10, 20, 30], [2, 3]]

             author        date
10     Егор Конюхов  2025-01-07
20     Андрей Фокин  2025-01-09
30  Михаил Подрезов  2025-01-10

Как быть, если нужные нам индексы или названия следуют друг за другом? Воспользоваться срезами (*slices*), как на списках или массивах!

> Выведите на экран заголовки и авторов новостей с индексами от 610 до 614 включительно. Используйте сначала `.loc`, а затем – `.iloc`.

In [17]:
# loc - правая граница среза включается
# строки с номерами от 610 до 614 включительно,
# столбцы от title до author включительно

news.loc[610:614, "title":"author"]

,title,author
610,Физики подули на одуванчики. Паппусы обычных р...,Егор Конюхов
611,Полые полупроницаемые волокна доставили кислор...,Анастасия Кузнецова–Фантони
612,В Венгрии обнаружили потенциальный череп Матья...,Михаил Подрезов
613,В древнем левантийском поселении изготавливали...,Михаил Подрезов
614,Робопчелу научили садиться по-комарьи. Чтобы и...,Андрей Фокин

In [18]:
# iloc - правая граница среза НЕ включается
# строки с номерами от 610 до 615, исключая 615
# столбцы с номерами от 1 до 3, исключая 3

news.iloc[610:615, 1:3]

,title,author
610,Физики подули на одуванчики. Паппусы обычных р...,Егор Конюхов
611,Полые полупроницаемые волокна доставили кислор...,Анастасия Кузнецова–Фантони
612,В Венгрии обнаружили потенциальный череп Матья...,Михаил Подрезов
613,В древнем левантийском поселении изготавливали...,Михаил Подрезов
614,Робопчелу научили садиться по-комарьи. Чтобы и...,Андрей Фокин

**Комментарий.** Так как метод `.iloc` работает исключительно с целочисленными индексами, он «наследует» поведение числовых срезов и функции `range()` в базовом Python – исключает правую границу диапазона, который мы выбираем. Метод `.loc` работает с текстовыми значениями в том числе, поэтому в нем срезы работают несколько иначе.

> Как выбрать все строки и один столбец, используя срезы? Или одну строку, но все столбцы? Выберите столбец `diffc`, а затем – строку с индексом 3.

In [19]:
# : – все строки от 0 до последней
news.loc[:, "diffc"]

0       2.9
1       3.1
2       2.3
3       4.1
4       1.2
       ...
1772    2.1
1773    4.2
1774    3.1
1775    1.3
1776    2.5
Name: diffc, Length: 1777, dtype: float64

In [20]:
# : – все столбцы от 0 до последнего

news.loc[3, :]

Unnamed: 0                                                    3
title         Виноградины усилили микроволновое поле и помог...
author                                             Егор Конюхов
date                                                 2025-01-06
diffc                                                       4.1
rubrics                                                  Физика
text          Физики использовали две виноградины для усилен...
Name: 3, dtype: object

## Часть 2: простое объединение датафреймов через `concat()`

Как мы уже видели, одна новость может относиться к нескольким рубрикам сразу:

In [21]:
print(news["rubrics"].unique())

['Физика, Геология' 'Археология, Антропология' 'Физика'
 'Медицина, Психология' 'Медицина' 'Астрономия' 'Психология, Медицина'
 'Физика, Биология' 'Авиация, Транспорт'
 'Антропология, Медицина, Археология' 'Ботаника, Экология и климат'
 'Роботы и дроны' 'Экология и климат, Зоология' 'Археология'
 'Медицина, Технологии' 'Палеонтология' 'Зоология, Экология и климат'
 'Космонавтика' 'Медицина, Экология и климат' 'Зоология'
 'Медицина, Биология' 'Экология и климат'
 'Антропология, Археология, История' 'Медицина, IT' 'IT, Мезонин'
 'Экология и климат, Психология, Медицина' 'Антропология' 'Мезонин, IT'
 'Антропология, Археология' 'Социология, Психология, Медицина' 'Биология'
 'Медицина, Социология' 'Биология, Медицина, Наука'
 'Медицина, Технологии, Социология, Психология' 'Биология, Медицина'
 'Археология, История' 'Психология, Социология'
 'Психология, Социология, Медицина' 'Химия' 'Физика, Астрономия'
 'Зоология, Антропология, Археология' 'Психология, Медицина, Технологии'
 'Авиация' 'Археология, Геология' 'Астрономия, Геология'
 'Роботы и дроны, Авиация' 'Психология, Технологии' 'Ботаника'
 'Археология, Лингвистика' 'Медицина, Связь' 'Геология' 'Психология'
 'Археология, Зоология' 'Физика, Материалы' 'Антропология, Палеонтология'
 'Астрономия, Физика' 'Археология, Биология' 'Медицина, Зоология'
 'Психология, Медицина, Гаджеты' 'Социология, Медицина'
 'Медицина, Гаджеты' 'Медицина, 3D-печать' 'IT, Биология, Мезонин'
 'Психология, IT, Гаджеты' 'История, Медицина' 'IT, Связь'
 'Экология и климат, Зоология, Ботаника' 'Археология, Ботаника'
 'Зоология, Биология' 'Психология, IT' 'Зоология, Ботаника' 'Гаджеты'
 'Экология и климат, Космонавтика' 'Биология, Медицина, 3D-печать'
 'Медицина, Психология, IT' 'Космонавтика, Роботы и дроны'
 'Медицина, Психология, Лингвистика' 'Медицина, Биология, Материалы'
 'Психология, IT, Медицина' 'Антропология, История'
 'Зоология, Палеонтология' 'Математика' 'Астрономия, Химия'
 'Палеонтология, Биология' 'Экология и климат, Ботаника'
 'Палеонтология, Зоология' 'Археология, Химия'
 'Медицина, Биология, Социология' 'Психология, Гаджеты'
 'Зоология, Экология и климат, Палеонтология' 'IT'
 'Медицина, Физика, Математика' 'Физика, Астрономия, IT'
 'Медицина, Социология, Психология' 'Биология, Зоология' 'История'
 'История, Зоология' 'Психология, Технологии, Медицина' 'Технологии'
 'Экология и климат, Медицина' 'История, Антропология'
 'Материалы, Биология' 'Транспорт' 'Физика, Математика, Ботаника'
 'Биология, Технологии' 'Зоология, Медицина' 'История, Археология'
 'Зоология, Экология и климат, Антропология' 'Зоология, Антропология'
 'IT, Гаджеты' 'Геология, Астрономия' 'Медицина, Роботы и дроны'
 'Космонавтика, Авиация' 'Материалы, Химия'
 'Зоология, Экология и климат, Медицина'
 'Ботаника, Экология и климат, Антропология'
 'Биология, Медицина, Психология' 'Лингвистика'
 'Палеонтология, Ботаника, Экология и климат' 'Зоология, Психология'
 'Инфопартнерство' 'Химия, Экология и климат' 'Социология, Психология'
 'Зоология, Медицина, Мезонин' 'Психология, Зоология'
 'Экология и климат, Авиация' 'Ботаника, Зоология'
 'Археология, Палеонтология' 'Антропология, История, Археология'
 'Зоология, Физика, Биология' 'Биология, Антропология'
 'Психология, Гаджеты, IT' 'IT, Лингвистика, История'
 'Физика, Биология, Медицина' 'Гаджеты, IT' 'Роботы и дроны, Зоология'
 'Психология, Игры' 'Медицина, Психология, Гаджеты'
 'Космонавтика, Биология' 'Биология, Химия' 'Химия, Медицина'
 'Психология, Гаджеты, Медицина' 'Зоология, IT' 'Физика, IT'
 'Зоология, Археология' 'Физика, Зоология' 'Зоология, История'
 'Ботаника, Химия, Биология' 'Зоология, Палеонтология, Экология и климат'
 'Медицина, Транспорт' 'Медицина, Психология, Социология' 'Наука'
 'Медицина, Психология, Экология и климат'
 'Медицина, Биология, Технологии' 'Экономика' 'Материалы'
 'Роботы и дроны, Мезонин, Ботаника' 'Зоология, Мезонин'
 'Психология, Социология, IT' 'Материалы, Экология и климат'
 'Экология и климат, Экономика' 'Экология и климат, Биология, Медицина'
 'IT, Психология' 'Археология, Физика' 'Археология, Экология и климат'
 'Биология, Палеонтология']

> Используя метод `.str.split()`, получите на основе столбца с рубриками новостей `rubrics` новые столбцы, где названия рубрик указаны по-отдельности. Сохраните новые столбцы в датафрейм `rubs`, присвойте им новые названия, записав их в атрибут датафрейма `.columns`.

In [22]:
rubs = news["rubrics"].str.split(", ", expand = True)
rubs.columns = ["rub1", "rub2", "rub3", "rub4"]
rubs

            rub1               rub2  rub3  rub4
0         Физика           Геология  None  None
1     Археология       Антропология  None  None
2         Физика               None  None  None
3         Физика               None  None  None
4       Медицина         Психология  None  None
...          ...                ...   ...   ...
1772    Зоология               None  None  None
1773  Астрономия               None  None  None
1774  Археология               None  None  None
1775  Археология               None  None  None
1776    Зоология  Экология и климат  None  None

[1777 rows x 4 columns]

> Используя функцию `concat()` из `pandas`, объедините датафреймы `news` и `rubs` в один итоговый датафрейм `final`. Выгрузите его в файл Excel.

In [23]:
# склеить по столбцам (axis = 1),
# а не по строкам (axis = 0 по умолчанию)

final = pd.concat([news, rubs], axis = 1)
final.head()

,Unnamed: 0,title,author,date,diffc,rubrics,text,rub1,rub2,rub3,rub4
0,0,Температуру ядра Земли уточнили с помощью лазе...,Егор Конюхов,2025-01-03,2.9,"Физика, Геология",Физики уточнили температуру внутренней границы...,Физика,Геология,None,None
1,1,Большинство людей эпохи мезолита из Оленеостро...,Михаил Подрезов,2025-01-03,3.1,"Археология, Антропология",Ученые проанализировали изотопный состав строн...,Археология,Антропология,None,None
2,2,Физики разобрались в состоянии покоя ткани. Он...,Егор Конюхов,2025-01-03,2.3,Физика,"Группа физиков выяснила, что при отсутствии вн...",Физика,None,None,None
3,3,Виноградины усилили микроволновое поле и помог...,Егор Конюхов,2025-01-06,4.1,Физика,Физики использовали две виноградины для усилен...,Физика,None,None,None
4,4,Прием глюкокортикоидов при беременности повыси...,Олег Лищук,2025-01-06,1.2,"Медицина, Психология",Кристина Лаугесен (Kristina Laugesen) из Орхус...,Медицина,Психология,None,None

In [24]:
final.to_excel("news.xlsx")

**Вопрос 1.** Как узнать, где лежит созданный файл `news.xlsx`? Импортировать модуль `os` (от *operating system*) для работы с операционной системой и запросить путь к текущей рабочей папке (*current working directory*) – той, где сейчас находится текущий ipynb-файл и все созданные во время работы файлы – с помощью функции `getcwd()`:

In [27]:
import os

In [28]:
# от get Current Working Directory
os.getcwd()

'C:\\Users\\Student'

Так, файл Excel надо искать в папке `C:\\Users\\Student`.

**Вопрос 2.** Как сохранить файл в другой папке? Прописать перед названием полный путь к желаемой папке, например:

In [ ]:
# на Windows, обратите внимание на r перед кавычками,
# если используются \\ или \

final.to_excel(r"C:\\Users\\Student\\Downloads\\news.xlsx")

In [ ]:
# на Windows, если используются обычные /

final.to_excel("C:/Users/Student/Downloads/news.xlsx")

In [ ]:
# на Mac/Linux, тут всегда обычные /

final.to_excel("/Users/allat/Desktop/data/news.xlsx")

**Примечание.** Символы `\` и `\\` считаются специальными, поскольку они имеют особый смысл (например, символ `&` в кодировке Unicode задается как `\u0026`), поэтому, чтобы Python при работе на Windows понимал, что мы имеем в виду обычные слэши между названиями папок и файлов в пути, перед кавычками нужно добавить `r`. Это рациональнее, чем вручную заменять все `\\` на корректно воспринимаемые `/` :)