# НИС «Основы анализа данных в Python»

*Алла Тамбовцева*

## Практикум 14. Корреляционная матрица и коэффициенты корреляции

### Корреляционная матрица

Импортируем `pandas` и загрузим данные из файла `Griliches.csv`:

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Griliches.csv")
df.head()

,rownames,rns,rns80,mrt,mrt80,smsa,smsa80,med,iq,kww,...,age,age80,school,school80,expr,expr80,tenure,tenure80,lw,lw80
0,1,no,no,no,yes,yes,yes,8,93,35,...,19,31,12,12,0.462,10.635,0,2,5.900,6.645
1,2,no,no,no,yes,yes,yes,14,119,41,...,23,37,16,18,0.000,11.367,2,16,5.438,6.694
2,3,no,no,no,yes,yes,yes,14,108,46,...,20,33,14,14,0.423,11.035,1,9,5.710,6.715
3,4,no,no,no,yes,yes,yes,12,96,32,...,18,32,12,12,0.333,13.089,1,7,5.481,6.477
4,5,no,no,yes,yes,yes,yes,6,74,27,...,26,34,9,11,9.013,14.402,3,5,5.927,6.332

Полное описание данных можно найти [здесь](https://vincentarelbundock.github.io/Rdatasets/doc/Ecdat/Griliches.html), это довольно древние данные, они используются в R как учебные данные для построения разных эконометрических моделей. Выберем классические показатели, которые часто изучают при рассмотрении факторов, от которых зависит заработная плата (здесь `lw` –  натуральный логарифм заработной платы):

* `age`: возраст;
* `expr`: опыт работы (стаж);
* `iq`:  коэффициент интеллекта IQ.

Так как все показатели числовые, можем построить для них **корреляционную матрицу**. По умолчанию это будет матрица с коэффициентами корреляции Пирсона:

In [3]:
df[["age", "lw", "expr", "iq"]].corr()

           age        lw      expr        iq
age   1.000000  0.534505  0.387501  0.177555
lw    0.534505  1.000000  0.084615  0.347069
expr  0.387501  0.084615  1.000000 -0.166253
iq    0.177555  0.347069 -0.166253  1.000000

Для удобства можем округлить все коэффициенты до сотых:

In [4]:
df[["age", "lw", "expr", "iq"]].corr().round(2)

       age    lw  expr    iq
age   1.00  0.53  0.39  0.18
lw    0.53  1.00  0.08  0.35
expr  0.39  0.08  1.00 -0.17
iq    0.18  0.35 -0.17  1.00

На главной диагонали матрицы стоят 1 – коэффициент Пирсона переменной самой с собой всегда равен 1. Почти все коэффициенты положительны: так, например, наблюдается умеренная положительная связь между возрастом и заработной платой (0.53), между возрастом и опытом работы (0.39), между заработной платой и уровнем IQ (0.35). Связь между заработной платой и опытом работы – слабая положительная (0.08), связь между возрастом и уровнем IQ – тоже (0.18). Слабая отрицательная связь слабой наблюдается между опытом работы и уровнем IQ (–0.17).

Для получения матрицы с коэффициентами корреляции Спирмена в метод `.corr()` нужно добавить аргумент `method = "spearman"`:

In [5]:
df[["age", "lw", "expr", "iq"]].corr(method = "spearman").round(2)

       age    lw  expr    iq
age   1.00  0.51  0.31  0.18
lw    0.51  1.00  0.08  0.35
expr  0.31  0.08  1.00 -0.12
iq    0.18  0.35 -0.12  1.00

Если в совместном распределении нет выбросов, значения коэффициента Пирсона и коэффициента Спирмена различаются несильно. Можем вычислить разницу между корреляционными матрицами (это два датафрейма одинаковой размерности) и убедиться в этом:

In [6]:
df[["age", "lw", 
    "expr", "iq"]].corr() - df[["age", "lw", 
                                "expr", "iq"]].corr(method = "spearman")

           age        lw      expr        iq
age   0.000000  0.025050  0.075882 -0.001915
lw    0.025050  0.000000  0.007871 -0.004845
expr  0.075882  0.007871  0.000000 -0.043311
iq   -0.001915 -0.004845 -0.043311  0.000000

**NB.** Если хочется оценить связь «всего со всем», то есть построить корреляционную матрицу для всех числовых переменных в датафрейме, в новых версиях `pandas` необходимо гарантировать, что мы применяем метод `.corr()` к датафрейму с соответствующими типами столбцов. Чтобы выбрать все числовые столбцы, можно воспользоваться методом `.select_dtypes()`:

In [7]:
# выбираем столбцы типов int, float

df.select_dtypes([int, float])

,rownames,med,iq,kww,year,age,age80,school,school80,expr,expr80,tenure,tenure80,lw,lw80
0,1,8,93,35,68,19,31,12,12,0.462,10.635,0,2,5.900,6.645
1,2,14,119,41,66,23,37,16,18,0.000,11.367,2,16,5.438,6.694
2,3,14,108,46,67,20,33,14,14,0.423,11.035,1,9,5.710,6.715
3,4,12,96,32,66,18,32,12,12,0.333,13.089,1,7,5.481,6.477
4,5,6,74,27,73,26,34,9,11,9.013,14.402,3,5,5.927,6.332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,754,8,113,45,71,26,35,16,16,0.000,8.205,1,10,6.023,7.274
754,755,7,93,39,67,22,35,12,12,0.692,10.737,1,3,5.176,6.469
755,756,12,101,38,73,25,33,12,12,4.828,10.589,0,5,5.784,6.467
756,757,7,100,33,73,23,31,12,12,2.489,9.004,2,3,5.628,6.168
757,758,8,102,32,68,19,31,12,13,0.277,9.834,1,3,5.075,7.092

In [8]:
# применяем .corr()

df.select_dtypes([int, float]).corr()

,rownames,med,iq,kww,year,age,age80,school,school80,expr,expr80,tenure,tenure80,lw,lw80
rownames,1.000000,-0.098059,-0.185482,-0.125443,-0.004557,-0.042677,-0.032500,-0.083868,-0.096995,-0.017501,-0.008201,-0.039472,-0.034021,-0.148645,-0.109164
med,-0.098059,1.000000,0.262826,0.195285,0.192482,0.103081,-0.047668,0.339561,0.341001,-0.158790,-0.180341,-0.047939,-0.039347,0.213232,0.190702
iq,-0.185482,0.262826,1.000000,0.339614,0.293102,0.177555,-0.051799,0.513118,0.514106,-0.166253,-0.229093,0.019392,0.008999,0.347069,0.260342
kww,-0.125443,0.195285,0.339614,1.000000,-0.015382,0.443969,0.444583,0.380950,0.371447,0.043237,0.049285,0.181750,0.148520,0.319434,0.309081
year,-0.004557,0.192482,0.293102,-0.015382,1.000000,0.351986,-0.410806,0.533528,0.516522,-0.000439,-0.557104,-0.103753,-0.204316,0.486749,0.022532
age,-0.042677,0.103081,0.177555,0.443969,0.351986,1.000000,0.705210,0.448150,0.431366,0.387501,0.056286,0.339067,0.132845,0.534505,0.226077
age80,-0.032500,-0.047668,-0.051799,0.444583,-0.410806,0.705210,1.000000,0.035940,0.031440,0.382289,0.479070,0.408663,0.288805,0.151635,0.198180
school,-0.083868,0.339561,0.513118,0.380950,0.533528,0.448150,0.035940,1.000000,0.959164,-0.241779,-0.390108,-0.049568,-0.021961,0.502738,0.333191
school80,-0.096995,0.341001,0.514106,0.371447,0.516522,0.431366,0.031440,0.959164,1.000000,-0.287548,-0.444970,-0.058623,-0.046234,0.483221,0.308991
expr,-0.017501,-0.158790,-0.166253,0.043237,-0.000439,0.387501,0.382289,-0.241779,-0.287548,1.000000,0.655387,0.230744,0.133993,0.084615,-0.021869
expr80,-0.008201,-0.180341,-0.229093,0.049285,-0.557104,0.056286,0.479070,-0.390108,-0.444970,0.655387,1.000000,0.249616,0.294294,-0.181313,0.053686
tenure,-0.039472,-0.047939,0.019392,0.181750,-0.103753,0.339067,0.408663,-0.049568,-0.058623,0.230744,0.249616,1.000000,0.337656,0.163767,0.105335
tenure80,-0.034021,-0.039347,0.008999,0.148520,-0.204316,0.132845,0.288805,-0.021961,-0.046234,0.133993,0.294294,0.337656,1.000000,0.046163,0.132852
lw,-0.148645,0.213232,0.347069,0.319434,0.486749,0.534505,0.151635,0.502738,0.483221,0.084615,-0.181313,0.163767,0.046163,1.000000,0.437304
lw80,-0.109164,0.190702,0.260342,0.309081,0.022532,0.226077,0.198180,0.333191,0.308991,-0.021869,0.053686,0.105335,0.132852,0.437304,1.000000

### Коэффициенты корреляции по группам

Данные в `df` – кросс-секционные, в таблице хранятся наблюдения за разные годы. Иногда имеет смысл оценивать связи между переменными по каждому году отдельно. Сфокусируемся на паре показателей `age` и `lw` и вычислим коэффициент Пирсона между ними за каждый год (столбец `year`):

In [10]:
# группируем по year,
# в каждой группе выбирем столбцы age, lw,
# применяем .corr()

df.groupby("year")[["age", "lw"]].corr()

               age        lw
year
66   age  1.000000  0.301575
     lw   0.301575  1.000000
67   age  1.000000  0.526589
     lw   0.526589  1.000000
68   age  1.000000  0.442663
     lw   0.442663  1.000000
69   age  1.000000  0.645821
     lw   0.645821  1.000000
70   age  1.000000  0.556441
     lw   0.556441  1.000000
71   age  1.000000  0.466684
     lw   0.466684  1.000000
73   age  1.000000  0.382206
     lw   0.382206  1.000000

Чисто технически, задача выполнена. Однако полученные результаты избыточны – метод `.corr()` возвращает корреляционную матрицу целиком, а нам достаточно одного коэффициента (1 на диагонали нас не интересует, а сам коэффициент дублируется). Чтобы понять, как извлечь один коэффициент, перепишем код выше, используя `.apply()` и lambda-функцию:

In [11]:
# тот же итог, что и выше

df.groupby("year")[["age", "lw"]].apply(lambda x: x.corr().round(2))

           age    lw
year
66   age  1.00  0.30
     lw   0.30  1.00
67   age  1.00  0.53
     lw   0.53  1.00
68   age  1.00  0.44
     lw   0.44  1.00
69   age  1.00  0.65
     lw   0.65  1.00
70   age  1.00  0.56
     lw   0.56  1.00
71   age  1.00  0.47
     lw   0.47  1.00
73   age  1.00  0.38
     lw   0.38  1.00

Что является результатом применения написанной lambda-функции к одной группе в `.groupby()`? Маленький датафрейм, который является корреляционной матрицей для двух переменных:

|             |   age |   lw |
|:------------|------:|-----:|
| **66** **age** |  1    | 0.3  |
| **66** **lw**  |  0.3  | 1    |

Чтобы забрать отсюда коэффициент 0.3, можно через метод `.iloc` выбрать элемент в первой строке и втором столбце или элемент во второй строке и первом столбце:

In [12]:
df.groupby("year")[["age", "lw"]].apply(lambda x: x.corr().iloc[0, 1].round(2))

year
66    0.30
67    0.53
68    0.44
69    0.65
70    0.56
71    0.47
73    0.38
dtype: float64

In [13]:
df.groupby("year")[["age", "lw"]].apply(lambda x: x.corr().iloc[1, 0].round(2))

year
66    0.30
67    0.53
68    0.44
69    0.65
70    0.56
71    0.47
73    0.38
dtype: float64

Теперь мы получили коэффициенты Пирсона между возрастом и заработной платой за каждый год отдельно.